config/routes.rb
Rails.application.routes.draw do
  root "landing#index"

  resources :users, only: [:new, :create, :show]

  resources :dreams, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dream.rb
class Dream < ApplicationRecord
  validates_presence_of :dream_title 
  validates_presence_of :user_id
  validates_presence_of :dream_content
  validates_presence_of :dream_date
  validates_presence_of :privacy_setting, allow_blank: true
  validates_presence_of :favorite, allow_blank: true
  validates_presence_of :additional_insights, allow_blank: true

  belongs_to :user
end

app/models/interpretation.rb
class Interpretation < ApplicationRecord
  validates_presence_of :dream_id
  validates_presence_of :interpretation_content

  belongs_to :dream
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 
  
  validates_presence_of :username, allow_nil: false, uniqueness: true
  validates :email,
  format: { with: /\A(.+)@(.+)\z/ },
  uniqueness: true,
  presence: true
  validates :password_digest, presence: true, confirmation: true
  has_secure_password

  has_many :dreams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotUnique, with: :not_unique_response
  helper_method :current_user

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def not_unique_response(error)
    flash[:error] = "User already exists."
    redirect_to new_user_path
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  def new
    @dream = Dream.new
  end

  def create
    @user = current_user
    @dream = @user.dreams.new(dream_params)
  
    if @dream.save
      flash[:alert] = "Entry saved."
      redirect_to user_path(@user)
    else
      flash[:alert] = "Required fields cannot be blank."
      render :new
    end
  end

  def show
    @dream = Dream.find_by(id: params[:id], user_id: session[:user_id])
  end
  

  private

  def dream_params
    params.require(:dream).permit(:dream_title, :dream_date, :dream_content, :additional_insights, :privacy_setting, :favorite)
  end  
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if params[:username] && params[:password]
      user = User.find_by(username: params[:username])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:success] = "Welcome, #{user.username}"
        redirect_to user_path(user)
      else
        flash[:alert] = "Invalid credentials."
        redirect_to login_path
      end
    end
  end

  def destroy
    session.delete(:user_id)
    @user = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
  
  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id 
      flash[:message] = "Account successfully created!"
      redirect_to user_path(@user.id)
    else
      if @user.errors[:email].present?
        flash[:error] = "User must enter a valid email address."
      else
        flash[:error] = "Fields cannot be blank."
      end
      redirect_to new_user_path
    end
  end
end


private

def user_params
  params.require(:user).permit(:username, :email, :password, :password_confirmation)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dreams/new.html.erb
<h3>Creating new dream entry...</h3>
<%= form_with model: @dream, url: dreams_path, method: :post do |f| %>
    <%= f.label :dream_title, 'Title*' %>
    <%= f.text_field :dream_title %>
    <br>
    <%= f.label :dream_date, 'Date of Dream*' %>
    <%= f.text_field :dream_date, as: :date %> 
    <br>
    <%= f.label :dream_content, 'Dream Content*' %>
    <%= f.text_area :dream_content %>
    <br>
    <%= f.label :additional_insights, 'Additional Insights' %>
    <%= f.text_area :additional_insights %>
    <br>
    <%= f.label :privacy_setting, 'Private?' %>
    <%= f.check_box :privacy_setting %>
    <br>
    <%= f.label :favorite, 'Favorite' %>
    <%= f.check_box :favorite %>
    <br>
    <%= f.submit 'Create Entry', data: {turbo: false} %>
<% end %>

app/views/dreams/show.html.erb
<%= @dream.dream_title %> -- <%= @dream.dream_date %>
<%= @dream.dream_content%>

app/views/landing/index.html.erb
<h3>Welcome to ReverieRealm</h3>
<% if current_user %>
  <%= link_to "My Dashboard", user_path(current_user.id) %>
<% else %>
  <%= link_to "Create an Account", new_user_path %><br>
  <%= link_to "Log In", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReverieRealm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <% flash.each do |type, message| %>
      <div class="alert alert-warning">
        <section class=<%= type %>>
          <strong><p><%= message %></p></strong>
        </section>
      </div>
  <% end %>

  <nav>
    <ul>
      <% if current_user %>
        <li><%= link_to 'Log Out', logout_path %></li>
      <% end %>
    </ul>
  </nav>


  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h2>Please Sign Up Below</h2>
<%= form_with model: @user do |f| %>
  <%= f.label :username, 'Username' %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :email, 'Email' %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit 'Create Account' %>
<% end %>

app/views/users/show.html.erb
<%= button_to "New Entry", new_dream_path, method: :get %>
<br>
<% @dreams = Dream.all %>
<% @dreams.each do |dream| %>
  <%= link_to dream.dream_title, dream_path(dream.id) %> -- <%= dream.dream_date %>
  <br>
  <%= dream.dream_content %>
<% end %>